apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "buildkit-operator.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "buildkit-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: buildd
